// <auto-generated />
using System;
using Grupp14_CV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grupp14_CV.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grupp14_CV.Models.CV", b =>
                {
                    b.Property<int>("CVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CVID"));

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PreviousExperience")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("CVID");

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            CVID = 1,
                            Competence = "Lösningsorienterad, tålmodig, klok.",
                            Content = "Hej! Jag heter Johan och är född 2001. Jag gillar mysiga hemmakvällar och att programmera.",
                            Education = "Europaskolan Gymnasie & Örebro Universitet Systemvetenskap",
                            Header = "Johans CV",
                            PreviousExperience = "Ica, Willys, Netbeans, Rewatch, SQL-Server, HTML, Alla språk."
                        },
                        new
                        {
                            CVID = 2,
                            Competence = "Noggrann, initiativrik, samarbetsvillig.",
                            Content = "Hej! Jag heter Anton och är född 1998. Jag gillar sport, teknik och att laga mat.",
                            Education = "Stockholms Universitet Datavetenskap",
                            Header = "Antons CV",
                            PreviousExperience = "Coop, Elgiganten, C#, React, Node.js, MongoDB."
                        },
                        new
                        {
                            CVID = 3,
                            Competence = "Ledarskapsförmåga, kreativ, kommunikativ.",
                            Content = "Hej! Jag heter William och är född 1995. Jag älskar att leda team, skapa lösningar och resa.",
                            Education = "Chalmers Tekniska Högskola Industriell Ekonomi",
                            Header = "Williams CV",
                            PreviousExperience = "Rewatch, Microsoft, Azure, Python, SQL, Vue.js."
                        },
                        new
                        {
                            CVID = 4,
                            Competence = "Analytisk, strukturerad, lösningsorienterad.",
                            Content = "Hej! Jag heter Oskar och är född 1997. Jag trivs med att arbeta med detaljer och analysera problem.",
                            Education = "Lunds Universitet Civilingenjör Informationsteknik",
                            Header = "Oskars CV",
                            PreviousExperience = "Hemköp, Rewatch, Java, Docker, Kubernetes, MySQL, PHP."
                        },
                        new
                        {
                            CVID = 5,
                            Competence = "Innovativ, användarcentrerad, flexibel.",
                            Content = "Hej! Jag heter Oliver och är född 2000. Jag brinner för ny teknik och att bygga intuitiva användarupplevelser.",
                            Education = "KTH Kungliga Tekniska Högskolan Datateknik",
                            Header = "Olivers CV",
                            PreviousExperience = "NetOnNet, MediaMarkt, Kotlin, Swift, Figma, UX/UI Design."
                        });
                });

            modelBuilder.Entity("Grupp14_CV.Models.Message", b =>
                {
                    b.Property<string>("SenderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiverID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.HasKey("SenderID", "ReceiverID");

                    b.HasIndex("ReceiverID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Grupp14_CV.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Grupp14_CV.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<int?>("CVID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("PublicSetting")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CVID")
                        .IsUnique()
                        .HasFilter("[CVID] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Grupp14_CV.Models.Users_In_Project", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Users_In_Projects");
                });

            modelBuilder.Entity("Grupp14_CV.Models.Message", b =>
                {
                    b.HasOne("Grupp14_CV.Models.User", "ReceiveUser")
                        .WithMany("RecievedMessages")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Grupp14_CV.Models.User", "SendUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReceiveUser");

                    b.Navigation("SendUser");
                });

            modelBuilder.Entity("Grupp14_CV.Models.Project", b =>
                {
                    b.HasOne("Grupp14_CV.Models.User", "user")
                        .WithMany("Projects")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Grupp14_CV.Models.User", b =>
                {
                    b.HasOne("Grupp14_CV.Models.CV", "CV")
                        .WithOne("Users")
                        .HasForeignKey("Grupp14_CV.Models.User", "CVID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CV");
                });

            modelBuilder.Entity("Grupp14_CV.Models.Users_In_Project", b =>
                {
                    b.HasOne("Grupp14_CV.Models.Project", "Project")
                        .WithMany("UsersInProject")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Grupp14_CV.Models.User", "User")
                        .WithMany("UsersInProject")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Grupp14_CV.Models.CV", b =>
                {
                    b.Navigation("Users")
                        .IsRequired();
                });

            modelBuilder.Entity("Grupp14_CV.Models.Project", b =>
                {
                    b.Navigation("UsersInProject");
                });

            modelBuilder.Entity("Grupp14_CV.Models.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("RecievedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UsersInProject");
                });
#pragma warning restore 612, 618
        }
    }
}
